### PR TITLE
Major structural changes/improvements

### PR DESCRIPTION
**Pull request by charlie0389**
- Significant restructuring of source files. There is now just 3 (renamed) source files, with the user typically only really needing to interact with one class - the HarFileObj class in the har_file.py file. The size of the code-base (in terms of lines of code) is now 37% smaller (excluding test code), without (as far as I'm aware) any loss of functionality.
- The behaviour of the original, which was to keep file pointers open until an object was destroyed, has been changed. File pointers are now only open if a read/write operation is underway. This makes for better behaved code in the event of a crash - on Windows heaps of unclosed file pointers were being created (which is not a healthy state to be in).
- Circular and improper dependencies removed.
- ​There are now tests (for all source files).
- There is now documentation.
- Breaks backwards compatibility with Python 2.
- Removed examples folder (examples no longer work).

### CODE REVIEW

**Comment by kalimaz0** [comment]
ViewHAR allows headers up to 4 characters maximum. With this merge any current HAR files with headers less than 4 characters are unable to be manipulated.

**Comment by charlie0389** [comment]
Hi @kalimaz0, I have now created a bug fix that allows for header names of less than 4 characters (adding spaces to the right to bring it up to 4). Given the size of the current pull request, and for the sake of cleanliness and avoiding confusion, I won't submit a pull request for the fix until this pull request is accepted.

**Comment by kalimaz0** [comment]
@charlie0389 Thank you for the quick fix.

**Comment by charlie0389** [comment]
Have now included that functionality in the pull request, plus convenience functions to recreate Tablo-like operations.

**Pull request merged**
